# MA261 Assignment 1

Student ID: 2106983

---

## Q 2.0.

In [1]:
import numpy as np
def npPrint(a, f={'float_kind':lambda x: "%.5e" % x}): 
   print( np.array2string(a, formatter=f) )

In [2]:
def forwardEuler( f,Df, t0,y0, h):
    return y0 + h*f(t0,y0)

In [3]:
def Q11(f,Df, t0,y0, h):
    x=f(t0,y0)
    y1=y0+(h/2)*(x+f(t0+h,y0+h*x))
    return y1

In [4]:
def evolve(phi, f,Df, t0,y0, T,N):
    n=np.arange(0,N+1,1)
    h=T/N
    t=n*h
    
    y=np.zeros((N+1,len(y0)))
    y[0]=y0
    for i in range(N):
        y[i+1]=phi(f,Df,t[i],y[i],h)
        
    return t,y

In [5]:
def computeEocs( herr ):
    m=np.size(herr,0)
    eocs=np.zeros(m-1)
    h=herr[:,0]
    e=herr[:,1]
    for i in range(m-1):
        eocs[i]=(np.log(e[i+1]/e[i])/np.log(h[i+1]/h[i]))
    return eocs

# Q 2.1.

In [6]:
def f(t,y):
    return np.array([y[1],y[1]*(1-2*y[0])])

def Y(t):
    Y=np.zeros(2)
    Y[0]=2*np.exp(t)/(2*np.exp(t)-1)
    Y[1]=-2*np.exp(t)/((2*np.exp(t)-1)**2)
    return Y

y0=np.array([2,-2])
T=10
N0=25
maxerr=np.zeros((10,2))

for i in range(10):
    err=[]
    N=N0*2**i
    h=T/N
    t,y=evolve(forwardEuler,f,0,0,y0,T,N)
    for j in range(np.shape(y)[0]):
        err.append(np.linalg.norm(y[j]-Y(t[j])))
    err=np.array(err)
    maxerr[i,:]=[h,np.max(err)]

npPrint(maxerr)
print()
print("So max errors are:")
npPrint(maxerr[:,1])
print()
print("EOCs are:")
npPrint(computeEocs(maxerr))

[[4.00000e-01 1.19752e+00]
 [2.00000e-01 3.84901e-01]
 [1.00000e-01 1.42446e-01]
 [5.00000e-02 6.52550e-02]
 [2.50000e-02 3.13566e-02]
 [1.25000e-02 1.53835e-02]
 [6.25000e-03 7.62053e-03]
 [3.12500e-03 3.79268e-03]
 [1.56250e-03 1.89197e-03]
 [7.81250e-04 9.44899e-04]]

So max errors are:
[1.19752e+00 3.84901e-01 1.42446e-01 6.52550e-02 3.13566e-02 1.53835e-02
 7.62053e-03 3.79268e-03 1.89197e-03 9.44899e-04]

EOCs are:
[1.63749e+00 1.43407e+00 1.12626e+00 1.05732e+00 1.02738e+00 1.01342e+00
 1.00668e+00 1.00333e+00 1.00166e+00]


# Q2.2.

In [7]:
def f(t,y):
    return np.array([y[1],y[1]*(1-2*y[0])])

def Y(t):
    Y=np.zeros(2)
    Y[0]=2*np.exp(t)/(2*np.exp(t)-1)
    Y[1]=-2*np.exp(t)/((2*np.exp(t)-1)**2)
    return Y

y0=np.array([2,-2])
T=10
N0=25
maxerr=np.zeros((10,2))

for i in range(10):
    err=[]
    N=N0*2**i
    h=T/N
    t,y=evolve(Q11,f,0,0,y0,T,N)
    for j in range(np.shape(y)[0]):
        err.append(np.linalg.norm(y[j]-Y(t[j])))
    err=np.array(err)
    maxerr[i,:]=[h,np.max(err)]
        
npPrint(maxerr)
print()
print("So max errors are:")
npPrint(maxerr[:,1])
print()
print("EOCs are:")
npPrint(computeEocs(maxerr))

[[4.00000e-01 2.33601e-01]
 [2.00000e-01 5.72438e-02]
 [1.00000e-01 1.25299e-02]
 [5.00000e-02 2.89433e-03]
 [2.50000e-02 6.88980e-04]
 [1.25000e-02 1.68007e-04]
 [6.25000e-03 4.14827e-05]
 [3.12500e-03 1.03058e-05]
 [1.56250e-03 2.56836e-06]
 [7.81250e-04 6.41080e-07]]

So max errors are:
[2.33601e-01 5.72438e-02 1.25299e-02 2.89433e-03 6.88980e-04 1.68007e-04
 4.14827e-05 1.03058e-05 2.56836e-06 6.41080e-07]

EOCs are:
[2.02886e+00 2.19174e+00 2.11408e+00 2.07069e+00 2.03594e+00 2.01794e+00
 2.00906e+00 2.00454e+00 2.00227e+00]


# Q2.3.

Every time evolve is called in Q2.1. f is evaluated $N$ times and evolve is called 10 times so f is evaluated $10N$ times. Similarly evolve is called 10 times in Q2.2. however each time it is called f is evaluated $2N$ so f is evaluated a total of $20N$ times. However, it can be seen as the EOCs converge to 2 in Q2.2. that the error converges quadratically whereas error convergence in Q2.1. is linear as the EOCs converge to 1.

# Q2.4.

In [8]:
def f(t,y):
     if (t<np.pi/2):
        return np.cos(t)

     return y

def Y(t):
    if (t<np.pi/2):
        Y=np.sin(t)
    
    else: 
        Y=np.exp(t-(np.pi/2))
    
    return Y

y0=np.array([0])
T=3
N0=25
maxerr=np.zeros((10,2))

for i in range(10):
    err=[]
    N=N0*2**i
    h=T/N
    t,y=evolve(forwardEuler,f,0,0,y0,T,N)
    for j in range(np.shape(y)[0]):
        err.append(np.abs(y[j]-Y(t[j])))
    err=np.array(err)
    maxerr[i,:]=[h,np.max(err)]
        
npPrint(maxerr)
print()
print("So max errors using Q 2.1. method are:")
npPrint(maxerr[:,1])
print()
print("EOCs using Q 2.1. are:")
npPrint(computeEocs(maxerr))
print()

for i in range(10):
    err=[]
    N=N0*2**i
    h=T/N
    t,y=evolve(Q11,f,0,0,y0,T,N)
    for j in range(np.shape(y)[0]):
        err.append(np.abs(y[j]-Y(t[j])))
    err=np.array(err)
    maxerr[i,:]=[h,np.max(err)]
        
npPrint(maxerr)
print()
print("So max errors using Q2.2. method are:")
npPrint(maxerr[:,1])
print()
print("EOCs using Q2.2 method are:")
npPrint(computeEocs(maxerr))

[[1.20000e-01 4.90234e-01]
 [6.00000e-02 2.41162e-01]
 [3.00000e-02 1.03184e-01]
 [1.50000e-02 3.04089e-02]
 [7.50000e-03 2.40459e-02]
 [3.75000e-03 5.22880e-03]
 [1.87500e-03 3.56577e-03]
 [9.37500e-04 2.73107e-03]
 [4.68750e-04 2.31293e-03]
 [2.34375e-04 1.12533e-03]]

So max errors using Q 2.1. method are:
[4.90234e-01 2.41162e-01 1.03184e-01 3.04089e-02 2.40459e-02 5.22880e-03
 3.56577e-03 2.73107e-03 2.31293e-03 1.12533e-03]

EOCs using Q 2.1. are:
[1.02347e+00 1.22478e+00 1.76266e+00 3.38699e-01 2.20124e+00 5.52268e-01
 3.84744e-01 2.39746e-01 1.03937e+00]

[[1.20000e-01 2.21094e-01]
 [6.00000e-02 8.45661e-02]
 [3.00000e-02 1.87087e-02]
 [1.50000e-02 1.34666e-02]
 [7.50000e-03 1.96899e-03]
 [3.75000e-03 5.91576e-03]
 [1.87500e-03 2.01545e-03]
 [9.37500e-04 6.17727e-05]
 [4.68750e-04 9.15947e-04]
 [2.34375e-04 4.26424e-04]]

So max errors using Q2.2. method are:
[2.21094e-01 8.45661e-02 1.87087e-02 1.34666e-02 1.96899e-03 5.91576e-03
 2.01545e-03 6.17727e-05 9.15947e-04 4.26424e-0

The erros for method Q 2.1. behave in no obvious order of h (linearly or quadratically etc) which contradicts what we know about the forward euler method that the errors converge linearly. This is further demonstrated by the EOCs as we would expect them to converge to 1 (the convergence rate) but there is clearly no convergence/ obvious patttern to the values.

Similarly, the errors for method Q2.2. do not show the quadratic order of convergence we showed in Q1.2. - there are decreases in h that lead to decreases in the error and some decreases in h that lead to increases in the error even. This is again further demonstrated by the EOCs as they do not clearly converge to any value.

This can be explained by the fact that the exact solution ${Y(t)}$ is in $C^1$ so it's second and third (and so on but not necessary for this) derivatives are not "smooth". We have seen that to use the forward euler method we need $Y'(t)$ to be "smooth" and for the Q2.2. method we need $Y''(t)$ to be smooth and as they are not this leads to our supposedly contradictory observations.